# order-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: demo-apps
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: order-service
          image: {{ .Values.orderService.image }}
          ports:
            - containerPort: {{ .Values.orderService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: demo-apps
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: {{ .Values.orderService.port }}
      targetPort: {{ .Values.orderService.port }}

---