apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      debug:
        verbosity: detailed

      otlphttp/honeycomb:
        endpoint: https://api.honeycomb.io
        headers:
          "x-honeycomb-team": "HONEYCOMB_API_KEY"
          "x-honeycomb-dataset": "springboot-demo"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlphttp/honeycomb]
        metrics:
          receivers: [otlp]
          exporters: [debug]
