apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest  # Pin version to avoid surprises
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      debug:
        verbosity: detailed   # replaces logging exporter
      otlp:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp]
        metrics:
          receivers: [otlp]
          exporters: [debug]
