apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.99.0
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      telemetry:
        metrics:
          address: ":8889"  # Expose metrics for Prometheus scraping
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp]

        metrics:
          receivers: [otlp]
          exporters: [debug]
