otelCollector:
  image: otel/opentelemetry-collector-contrib:0.99.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: jaeger.observability.svc.cluster.local:14250
        insecure: true

    processors:
      batch: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

jaeger:
  enabled: true
  image: jaegertracing/all-in-one:1.52.0
